[{"ip_address": "192.168.30.151", "date": "25-08-2022", "time": "17-34-41", "reason": "Failed to login to host"}, {"ip_address": "192.168.30.154", "date": "25-08-2022", "time": "17-34-41", "reason": "Failed to login to host"}, {"ip_address": "sandbox-iosxe-latest-1.cisco.com", "date": "25-08-2022", "time": "17-34-41", "reason": "Failed to login to host"}, {"ip_address": "192.168.30.152", "date": "25-08-2022", "time": "17-34-41", "reason": "Failed to login to host"}, {"ip_address": "192.156.30.157", "date": "25-08-2022", "time": "17-34-41", "reason": "Failed to login to host"}, {"ip_address": "192.168.30.151", "date": "25-08-2022", "time": "17-34-55", "reason": "Failed to login to host"}, {"ip_address": "192.168.30.152", "date": "25-08-2022", "time": "17-34-55", "reason": "Failed to login to host"}, {"ip_address": "192.168.30.154", "date": "25-08-2022", "time": "17-34-55", "reason": "Failed to login to host"}, {"ip_address": "192.156.30.157", "date": "25-08-2022", "time": "17-34-55", "reason": "Failed to login to host"}, {"ip_address": "sandbox-iosxe-latest-1.cisco.com", "date": "25-08-2022", "time": "17-34-55", "reason": "Failed to login to host"}, {"ip_address": "192.168.30.151", "date": "25-08-2022", "time": "17-40-32", "reason": "Failed to login to host"}, {"ip_address": "192.168.30.154", "date": "25-08-2022", "time": "17-40-32", "reason": "Failed to login to host"}, {"ip_address": "192.168.30.152", "date": "25-08-2022", "time": "17-40-32", "reason": "Failed to login to host"}, {"ip_address": "sandbox-iosxe-latest-1.cisco.com", "date": "25-08-2022", "time": "17-40-32", "reason": "Failed to login to host"}, {"ip_address": "192.156.30.157", "date": "25-08-2022", "time": "17-40-32", "reason": "Failed to login to host"}, {"ip_address": "192.168.30.151", "date": "25-08-2022", "time": "17-40-41", "reason": "Failed to login to host"}, {"ip_address": "192.168.30.152", "date": "25-08-2022", "time": "17-40-41", "reason": "Failed to login to host"}, {"ip_address": "192.168.30.154", "date": "25-08-2022", "time": "17-40-41", "reason": "Failed to login to host"}, {"ip_address": "192.156.30.157", "date": "25-08-2022", "time": "17-40-41", "reason": "Failed to login to host"}, {"ip_address": "sandbox-iosxe-latest-1.cisco.com", "date": "25-08-2022", "time": "17-40-41", "reason": "Failed to login to host"}, {"ip_address": "192.168.30.151", "date": "25-08-2022", "time": "17-42-28", "reason": "Failed to login to host"}, {"ip_address": "192.168.30.152", "date": "25-08-2022", "time": "17-42-28", "reason": "Failed to login to host"}, {"ip_address": "192.168.30.154", "date": "25-08-2022", "time": "17-42-28", "reason": "Failed to login to host"}, {"ip_address": "sandbox-iosxe-latest-1.cisco.com", "date": "25-08-2022", "time": "17-42-28", "reason": "Failed to login to host"}, {"ip_address": "192.156.30.157", "date": "25-08-2022", "time": "17-42-28", "reason": "Failed to login to host"}, {"ip_address": "192.168.30.152", "date": "25-08-2022", "time": "18-13-15", "reason": "Failed to login to host"}, {"ip_address": "192.168.30.151", "date": "25-08-2022", "time": "18-13-15", "reason": "Failed to login to host"}, {"ip_address": "192.156.30.157", "date": "25-08-2022", "time": "18-13-15", "reason": "Failed to login to host"}, {"ip_address": "192.168.30.154", "date": "25-08-2022", "time": "18-13-15", "reason": "Failed to login to host"}, {"ip_address": "sandbox-iosxe-latest-1.cisco.com", "date": "25-08-2022", "time": "18-13-15", "reason": "Failed to login to host"}, {"ip_address": "192.168.30.152", "date": "25-08-2022", "time": "18-13-48", "reason": "Exception Occured while Parsing Vlan Keys 'str' object has no attribute 'pop'"}, {"ip_address": "192.168.30.151", "date": "25-08-2022", "time": "18-13-48", "reason": "Exception Occured while Parsing Vlan Keys 'str' object has no attribute 'pop'"}, {"ip_address": "192.168.30.152", "date": "25-08-2022", "time": "18-13-49", "reason": "Failed to insert Data to DB 'time'"}, {"ip_address": "192.168.30.151", "date": "25-08-2022", "time": "18-13-49", "reason": "Failed to insert Data to DB 'time'"}, {"ip_address": "sandbox-iosxe-latest-1.cisco.com", "date": "25-08-2022", "time": "18-14-18", "reason": "Exception Occured while Parsing Vlan Keys 'str' object has no attribute 'pop'"}, {"ip_address": "sandbox-iosxe-latest-1.cisco.com", "date": "25-08-2022", "time": "18-14-21", "reason": "Failed to insert Data to DB 'time'"}, {"ip_address": "sandbox-iosxe-latest-1.cisco.com", "date": "25-08-2022", "time": "18-14-21", "reason": "Failed to insert Data to DB 'time'"}, {"ip_address": "sandbox-iosxe-latest-1.cisco.com", "date": "25-08-2022", "time": "18-14-21", "reason": "Failed to insert Data to DB 'time'"}, {"ip_address": "192.156.30.157", "date": "25-08-2022", "time": "18-14-31", "reason": "Failed to login to host"}, {"ip_address": "192.168.30.154", "date": "25-08-2022", "time": "18-14-31", "reason": "Failed to login to host"}, {"ip_address": "192.168.30.152", "date": "25-08-2022", "time": "18-16-34", "reason": "Exception Occured while Parsing Vlan Keys 'str' object has no attribute 'pop'"}, {"ip_address": "192.168.30.151", "date": "25-08-2022", "time": "18-16-35", "reason": "Exception Occured while Parsing Vlan Keys 'str' object has no attribute 'pop'"}, {"ip_address": "192.168.30.152", "date": "25-08-2022", "time": "18-16-35", "reason": "Failed to insert Data to DB (pymysql.err.OperationalError) (1054, \"Unknown column 'device_name' in 'field list'\")\n[SQL: INSERT INTO ipam_devices_fetch_table (ip_address, device_name, interface, interface_ip, subnet, subnet_mask, interface_description, virtual_ip, vlan, vlan_number, interface_status, fetch_date) VALUES (%(ip_address)s, %(device_name)s, %(interface)s, %(interface_ip)s, %(subnet)s, %(subnet_mask)s, %(interface_description)s, %(virtual_ip)s, %(vlan)s, %(vlan_number)s, %(interface_status)s, %(fetch_date)s)]\n[parameters: {'ip_address': '192.168.30.152', 'device_name': '', 'interface': 'Ethernet1/0', 'interface_ip': '', 'subnet': '192.168.30.0/24', 'subnet_mask': IPAddress('255.255.255.0'), 'interface_description': '', 'virtual_ip': '', 'vlan': None, 'vlan_number': '', 'interface_status': 'up', 'fetch_date': datetime.datetime(2022, 8, 25, 18, 16, 27, 431335)}]\n(Background on this error at: http://sqlalche.me/e/13/e3q8)"}, {"ip_address": "192.168.30.151", "date": "25-08-2022", "time": "18-16-36", "reason": "Failed to insert Data to DB (pymysql.err.OperationalError) (1054, \"Unknown column 'device_name' in 'field list'\")\n[SQL: INSERT INTO ipam_devices_fetch_table (ip_address, device_name, interface, interface_ip, subnet, subnet_mask, interface_description, virtual_ip, vlan, vlan_number, interface_status, fetch_date) VALUES (%(ip_address)s, %(device_name)s, %(interface)s, %(interface_ip)s, %(subnet)s, %(subnet_mask)s, %(interface_description)s, %(virtual_ip)s, %(vlan)s, %(vlan_number)s, %(interface_status)s, %(fetch_date)s)]\n[parameters: {'ip_address': '192.168.30.151', 'device_name': '', 'interface': 'Ethernet2/0', 'interface_ip': '', 'subnet': '192.168.30.0/24', 'subnet_mask': IPAddress('255.255.255.0'), 'interface_description': '', 'virtual_ip': '', 'vlan': None, 'vlan_number': '', 'interface_status': 'up', 'fetch_date': datetime.datetime(2022, 8, 25, 18, 16, 27, 431324)}]\n(Background on this error at: http://sqlalche.me/e/13/e3q8)"}, {"ip_address": "sandbox-iosxe-latest-1.cisco.com", "date": "25-08-2022", "time": "18-16-55", "reason": "Exception Occured while Parsing Vlan Keys 'str' object has no attribute 'pop'"}, {"ip_address": "sandbox-iosxe-latest-1.cisco.com", "date": "25-08-2022", "time": "18-16-58", "reason": "Failed to insert Data to DB (pymysql.err.OperationalError) (1054, \"Unknown column 'device_name' in 'field list'\")\n[SQL: INSERT INTO ipam_devices_fetch_table (ip_address, device_name, interface, interface_ip, subnet, subnet_mask, interface_description, virtual_ip, vlan, vlan_number, interface_status, fetch_date) VALUES (%(ip_address)s, %(device_name)s, %(interface)s, %(interface_ip)s, %(subnet)s, %(subnet_mask)s, %(interface_description)s, %(virtual_ip)s, %(vlan)s, %(vlan_number)s, %(interface_status)s, %(fetch_date)s)]\n[parameters: {'ip_address': 'sandbox-iosxe-latest-1.cisco.com', 'device_name': '', 'interface': 'GigabitEthernet1', 'interface_ip': '', 'subnet': '10.10.20.0/24', 'subnet_mask': IPAddress('255.255.255.0'), 'interface_description': \"MANAGEMENT INTERFACE - DON'T TOUCH ME\", 'virtual_ip': '', 'vlan': None, 'vlan_number': '', 'interface_status': 'up', 'fetch_date': datetime.datetime(2022, 8, 25, 18, 16, 27, 431341)}]\n(Background on this error at: http://sqlalche.me/e/13/e3q8)"}, {"ip_address": "sandbox-iosxe-latest-1.cisco.com", "date": "25-08-2022", "time": "18-16-58", "reason": "Failed to insert Data to DB (pymysql.err.OperationalError) (1054, \"Unknown column 'device_name' in 'field list'\")\n[SQL: INSERT INTO ipam_devices_fetch_table (ip_address, device_name, interface, interface_ip, subnet, subnet_mask, interface_description, virtual_ip, vlan, vlan_number, interface_status, fetch_date) VALUES (%(ip_address)s, %(device_name)s, %(interface)s, %(interface_ip)s, %(subnet)s, %(subnet_mask)s, %(interface_description)s, %(virtual_ip)s, %(vlan)s, %(vlan_number)s, %(interface_status)s, %(fetch_date)s)]\n[parameters: {'ip_address': 'sandbox-iosxe-latest-1.cisco.com', 'device_name': '', 'interface': 'Loopback2', 'interface_ip': '', 'subnet': '1.1.1.1/32', 'subnet_mask': IPAddress('255.255.255.255'), 'interface_description': 'Configured by RESTCONF', 'virtual_ip': '', 'vlan': None, 'vlan_number': '', 'interface_status': 'up', 'fetch_date': datetime.datetime(2022, 8, 25, 18, 16, 27, 431341)}]\n(Background on this error at: http://sqlalche.me/e/13/e3q8)"}, {"ip_address": "sandbox-iosxe-latest-1.cisco.com", "date": "25-08-2022", "time": "18-16-58", "reason": "Failed to insert Data to DB (pymysql.err.OperationalError) (1054, \"Unknown column 'device_name' in 'field list'\")\n[SQL: INSERT INTO ipam_devices_fetch_table (ip_address, device_name, interface, interface_ip, subnet, subnet_mask, interface_description, virtual_ip, vlan, vlan_number, interface_status, fetch_date) VALUES (%(ip_address)s, %(device_name)s, %(interface)s, %(interface_ip)s, %(subnet)s, %(subnet_mask)s, %(interface_description)s, %(virtual_ip)s, %(vlan)s, %(vlan_number)s, %(interface_status)s, %(fetch_date)s)]\n[parameters: {'ip_address': 'sandbox-iosxe-latest-1.cisco.com', 'device_name': '', 'interface': 'Loopback11', 'interface_ip': '', 'subnet': '172.16.11.0/24', 'subnet_mask': IPAddress('255.255.255.0'), 'interface_description': 'Configured by RESTCONF', 'virtual_ip': '', 'vlan': None, 'vlan_number': '', 'interface_status': 'up', 'fetch_date': datetime.datetime(2022, 8, 25, 18, 16, 27, 431341)}]\n(Background on this error at: http://sqlalche.me/e/13/e3q8)"}, {"ip_address": "192.168.30.154", "date": "25-08-2022", "time": "18-17-17", "reason": "Failed to login to host"}, {"ip_address": "192.156.30.157", "date": "25-08-2022", "time": "18-17-17", "reason": "Failed to login to host"}, {"ip_address": "192.168.30.152", "date": "25-08-2022", "time": "18-20-39", "reason": "Exception Occured while Parsing Vlan Keys 'str' object has no attribute 'pop'"}, {"ip_address": "192.168.30.151", "date": "25-08-2022", "time": "18-20-39", "reason": "Exception Occured while Parsing Vlan Keys 'str' object has no attribute 'pop'"}, {"ip_address": "192.168.30.152", "date": "25-08-2022", "time": "18-20-40", "reason": "Failed to insert Data to DB 'device_name'"}, {"ip_address": "192.168.30.151", "date": "25-08-2022", "time": "18-20-40", "reason": "Failed to insert Data to DB 'device_name'"}, {"ip_address": "sandbox-iosxe-latest-1.cisco.com", "date": "25-08-2022", "time": "18-21-00", "reason": "Exception Occured while Parsing Vlan Keys 'str' object has no attribute 'pop'"}, {"ip_address": "sandbox-iosxe-latest-1.cisco.com", "date": "25-08-2022", "time": "18-21-02", "reason": "Failed to insert Data to DB 'device_name'"}, {"ip_address": "sandbox-iosxe-latest-1.cisco.com", "date": "25-08-2022", "time": "18-21-02", "reason": "Failed to insert Data to DB 'device_name'"}, {"ip_address": "sandbox-iosxe-latest-1.cisco.com", "date": "25-08-2022", "time": "18-21-02", "reason": "Failed to insert Data to DB 'device_name'"}, {"ip_address": "192.168.30.154", "date": "25-08-2022", "time": "18-21-22", "reason": "Failed to login to host"}, {"ip_address": "192.156.30.157", "date": "25-08-2022", "time": "18-21-22", "reason": "Failed to login to host"}, {"ip_address": "192.168.30.152", "date": "25-08-2022", "time": "18-22-18", "reason": "Exception Occured while Parsing Vlan Keys 'str' object has no attribute 'pop'"}, {"ip_address": "192.168.30.151", "date": "25-08-2022", "time": "18-22-18", "reason": "Exception Occured while Parsing Vlan Keys 'str' object has no attribute 'pop'"}, {"ip_address": "192.168.30.152", "date": "25-08-2022", "time": "18-22-19", "reason": "Failed to insert Data to DB (pymysql.err.OperationalError) (1054, \"Unknown column 'device_name' in 'field list'\")\n[SQL: INSERT INTO ipam_devices_fetch_table (ip_address, device_name, interface, interface_ip, subnet, subnet_mask, interface_description, virtual_ip, vlan, vlan_number, interface_status, fetch_date) VALUES (%(ip_address)s, %(device_name)s, %(interface)s, %(interface_ip)s, %(subnet)s, %(subnet_mask)s, %(interface_description)s, %(virtual_ip)s, %(vlan)s, %(vlan_number)s, %(interface_status)s, %(fetch_date)s)]\n[parameters: {'ip_address': '192.168.30.152', 'device_name': 'Switch4', 'interface': 'Ethernet1/0', 'interface_ip': '', 'subnet': '192.168.30.0/24', 'subnet_mask': IPAddress('255.255.255.0'), 'interface_description': '', 'virtual_ip': '', 'vlan': None, 'vlan_number': '', 'interface_status': 'up', 'fetch_date': datetime.datetime(2000, 1, 1, 0, 0)}]\n(Background on this error at: http://sqlalche.me/e/13/e3q8)"}, {"ip_address": "192.168.30.151", "date": "25-08-2022", "time": "18-22-20", "reason": "Failed to insert Data to DB (pymysql.err.OperationalError) (1054, \"Unknown column 'device_name' in 'field list'\")\n[SQL: INSERT INTO ipam_devices_fetch_table (ip_address, device_name, interface, interface_ip, subnet, subnet_mask, interface_description, virtual_ip, vlan, vlan_number, interface_status, fetch_date) VALUES (%(ip_address)s, %(device_name)s, %(interface)s, %(interface_ip)s, %(subnet)s, %(subnet_mask)s, %(interface_description)s, %(virtual_ip)s, %(vlan)s, %(vlan_number)s, %(interface_status)s, %(fetch_date)s)]\n[parameters: {'ip_address': '192.168.30.151', 'device_name': 'Switch1', 'interface': 'Ethernet2/0', 'interface_ip': '', 'subnet': '192.168.30.0/24', 'subnet_mask': IPAddress('255.255.255.0'), 'interface_description': '', 'virtual_ip': '', 'vlan': None, 'vlan_number': '', 'interface_status': 'up', 'fetch_date': datetime.datetime(2000, 1, 1, 0, 0)}]\n(Background on this error at: http://sqlalche.me/e/13/e3q8)"}, {"ip_address": "sandbox-iosxe-latest-1.cisco.com", "date": "25-08-2022", "time": "18-22-38", "reason": "Exception Occured while Parsing Vlan Keys 'str' object has no attribute 'pop'"}, {"ip_address": "sandbox-iosxe-latest-1.cisco.com", "date": "25-08-2022", "time": "18-22-40", "reason": "Failed to insert Data to DB (pymysql.err.OperationalError) (1054, \"Unknown column 'device_name' in 'field list'\")\n[SQL: INSERT INTO ipam_devices_fetch_table (ip_address, device_name, interface, interface_ip, subnet, subnet_mask, interface_description, virtual_ip, vlan, vlan_number, interface_status, fetch_date) VALUES (%(ip_address)s, %(device_name)s, %(interface)s, %(interface_ip)s, %(subnet)s, %(subnet_mask)s, %(interface_description)s, %(virtual_ip)s, %(vlan)s, %(vlan_number)s, %(interface_status)s, %(fetch_date)s)]\n[parameters: {'ip_address': 'sandbox-iosxe-latest-1.cisco.com', 'device_name': 'Switch6', 'interface': 'GigabitEthernet1', 'interface_ip': '', 'subnet': '10.10.20.0/24', 'subnet_mask': IPAddress('255.255.255.0'), 'interface_description': \"MANAGEMENT INTERFACE - DON'T TOUCH ME\", 'virtual_ip': '', 'vlan': None, 'vlan_number': '', 'interface_status': 'up', 'fetch_date': datetime.datetime(2000, 1, 1, 0, 0)}]\n(Background on this error at: http://sqlalche.me/e/13/e3q8)"}, {"ip_address": "sandbox-iosxe-latest-1.cisco.com", "date": "25-08-2022", "time": "18-22-40", "reason": "Failed to insert Data to DB (pymysql.err.OperationalError) (1054, \"Unknown column 'device_name' in 'field list'\")\n[SQL: INSERT INTO ipam_devices_fetch_table (ip_address, device_name, interface, interface_ip, subnet, subnet_mask, interface_description, virtual_ip, vlan, vlan_number, interface_status, fetch_date) VALUES (%(ip_address)s, %(device_name)s, %(interface)s, %(interface_ip)s, %(subnet)s, %(subnet_mask)s, %(interface_description)s, %(virtual_ip)s, %(vlan)s, %(vlan_number)s, %(interface_status)s, %(fetch_date)s)]\n[parameters: {'ip_address': 'sandbox-iosxe-latest-1.cisco.com', 'device_name': 'Switch6', 'interface': 'Loopback2', 'interface_ip': '', 'subnet': '1.1.1.1/32', 'subnet_mask': IPAddress('255.255.255.255'), 'interface_description': 'Configured by RESTCONF', 'virtual_ip': '', 'vlan': None, 'vlan_number': '', 'interface_status': 'up', 'fetch_date': datetime.datetime(2000, 1, 1, 0, 0)}]\n(Background on this error at: http://sqlalche.me/e/13/e3q8)"}, {"ip_address": "sandbox-iosxe-latest-1.cisco.com", "date": "25-08-2022", "time": "18-22-40", "reason": "Failed to insert Data to DB (pymysql.err.OperationalError) (1054, \"Unknown column 'device_name' in 'field list'\")\n[SQL: INSERT INTO ipam_devices_fetch_table (ip_address, device_name, interface, interface_ip, subnet, subnet_mask, interface_description, virtual_ip, vlan, vlan_number, interface_status, fetch_date) VALUES (%(ip_address)s, %(device_name)s, %(interface)s, %(interface_ip)s, %(subnet)s, %(subnet_mask)s, %(interface_description)s, %(virtual_ip)s, %(vlan)s, %(vlan_number)s, %(interface_status)s, %(fetch_date)s)]\n[parameters: {'ip_address': 'sandbox-iosxe-latest-1.cisco.com', 'device_name': 'Switch6', 'interface': 'Loopback11', 'interface_ip': '', 'subnet': '172.16.11.0/24', 'subnet_mask': IPAddress('255.255.255.0'), 'interface_description': 'Configured by RESTCONF', 'virtual_ip': '', 'vlan': None, 'vlan_number': '', 'interface_status': 'up', 'fetch_date': datetime.datetime(2000, 1, 1, 0, 0)}]\n(Background on this error at: http://sqlalche.me/e/13/e3q8)"}, {"ip_address": "192.156.30.157", "date": "25-08-2022", "time": "18-23-01", "reason": "Failed to login to host"}, {"ip_address": "192.168.30.154", "date": "25-08-2022", "time": "18-23-01", "reason": "Failed to login to host"}, {"ip_address": "192.168.30.152", "date": "25-08-2022", "time": "18-23-44", "reason": "Exception Occured while Parsing Vlan Keys 'str' object has no attribute 'pop'"}, {"ip_address": "192.168.30.151", "date": "25-08-2022", "time": "18-23-45", "reason": "Exception Occured while Parsing Vlan Keys 'str' object has no attribute 'pop'"}, {"ip_address": "sandbox-iosxe-latest-1.cisco.com", "date": "25-08-2022", "time": "18-24-05", "reason": "Exception Occured while Parsing Vlan Keys 'str' object has no attribute 'pop'"}, {"ip_address": "sandbox-iosxe-latest-1.cisco.com", "date": "25-08-2022", "time": "18-24-07", "reason": "Failed to insert Data to DB (pymysql.err.IntegrityError) (1062, \"Duplicate entry 'sandbox-iosxe-latest-1.cisco.com' for key 'ipam_devices_fetch_table.IP_ADDRESS'\")\n[SQL: INSERT INTO ipam_devices_fetch_table (ip_address, device_name, interface, interface_ip, subnet, subnet_mask, interface_description, virtual_ip, vlan, vlan_number, interface_status, fetch_date) VALUES (%(ip_address)s, %(device_name)s, %(interface)s, %(interface_ip)s, %(subnet)s, %(subnet_mask)s, %(interface_description)s, %(virtual_ip)s, %(vlan)s, %(vlan_number)s, %(interface_status)s, %(fetch_date)s)]\n[parameters: {'ip_address': 'sandbox-iosxe-latest-1.cisco.com', 'device_name': 'Switch6', 'interface': 'Loopback2', 'interface_ip': '', 'subnet': '1.1.1.1/32', 'subnet_mask': IPAddress('255.255.255.255'), 'interface_description': 'Configured by RESTCONF', 'virtual_ip': '', 'vlan': None, 'vlan_number': '', 'interface_status': 'up', 'fetch_date': datetime.datetime(2000, 1, 1, 0, 0)}]\n(Background on this error at: http://sqlalche.me/e/13/gkpj)"}, {"ip_address": "sandbox-iosxe-latest-1.cisco.com", "date": "25-08-2022", "time": "18-24-07", "reason": "Failed to insert Data to DB (pymysql.err.IntegrityError) (1062, \"Duplicate entry 'sandbox-iosxe-latest-1.cisco.com' for key 'ipam_devices_fetch_table.IP_ADDRESS'\")\n[SQL: INSERT INTO ipam_devices_fetch_table (ip_address, device_name, interface, interface_ip, subnet, subnet_mask, interface_description, virtual_ip, vlan, vlan_number, interface_status, fetch_date) VALUES (%(ip_address)s, %(device_name)s, %(interface)s, %(interface_ip)s, %(subnet)s, %(subnet_mask)s, %(interface_description)s, %(virtual_ip)s, %(vlan)s, %(vlan_number)s, %(interface_status)s, %(fetch_date)s)]\n[parameters: {'ip_address': 'sandbox-iosxe-latest-1.cisco.com', 'device_name': 'Switch6', 'interface': 'Loopback11', 'interface_ip': '', 'subnet': '172.16.11.0/24', 'subnet_mask': IPAddress('255.255.255.0'), 'interface_description': 'Configured by RESTCONF', 'virtual_ip': '', 'vlan': None, 'vlan_number': '', 'interface_status': 'up', 'fetch_date': datetime.datetime(2000, 1, 1, 0, 0)}]\n(Background on this error at: http://sqlalche.me/e/13/gkpj)"}, {"ip_address": "192.168.30.154", "date": "25-08-2022", "time": "18-24-27", "reason": "Failed to login to host"}, {"ip_address": "192.156.30.157", "date": "25-08-2022", "time": "18-24-27", "reason": "Failed to login to host"}, {"ip_address": "192.168.30.152", "date": "25-08-2022", "time": "18-25-21", "reason": "Exception Occured while Parsing Vlan Keys 'str' object has no attribute 'pop'"}, {"ip_address": "192.168.30.151", "date": "25-08-2022", "time": "18-25-21", "reason": "Exception Occured while Parsing Vlan Keys 'str' object has no attribute 'pop'"}, {"ip_address": "sandbox-iosxe-latest-1.cisco.com", "date": "25-08-2022", "time": "18-25-42", "reason": "Exception Occured while Parsing Vlan Keys 'str' object has no attribute 'pop'"}, {"ip_address": "sandbox-iosxe-latest-1.cisco.com", "date": "25-08-2022", "time": "18-25-44", "reason": "Failed to insert Data to DB (pymysql.err.IntegrityError) (1062, \"Duplicate entry 'sandbox-iosxe-latest-1.cisco.com' for key 'ipam_devices_fetch_table.IP_ADDRESS'\")\n[SQL: INSERT INTO ipam_devices_fetch_table (ip_address, device_name, interface, interface_ip, subnet, subnet_mask, interface_description, virtual_ip, vlan, vlan_number, interface_status, fetch_date) VALUES (%(ip_address)s, %(device_name)s, %(interface)s, %(interface_ip)s, %(subnet)s, %(subnet_mask)s, %(interface_description)s, %(virtual_ip)s, %(vlan)s, %(vlan_number)s, %(interface_status)s, %(fetch_date)s)]\n[parameters: {'ip_address': 'sandbox-iosxe-latest-1.cisco.com', 'device_name': 'Switch6', 'interface': 'Loopback2', 'interface_ip': '', 'subnet': '1.1.1.1/32', 'subnet_mask': IPAddress('255.255.255.255'), 'interface_description': 'Configured by RESTCONF', 'virtual_ip': '', 'vlan': None, 'vlan_number': '', 'interface_status': 'up', 'fetch_date': datetime.datetime(2000, 1, 1, 0, 0)}]\n(Background on this error at: http://sqlalche.me/e/13/gkpj)"}, {"ip_address": "sandbox-iosxe-latest-1.cisco.com", "date": "25-08-2022", "time": "18-25-44", "reason": "Failed to insert Data to DB (pymysql.err.IntegrityError) (1062, \"Duplicate entry 'sandbox-iosxe-latest-1.cisco.com' for key 'ipam_devices_fetch_table.IP_ADDRESS'\")\n[SQL: INSERT INTO ipam_devices_fetch_table (ip_address, device_name, interface, interface_ip, subnet, subnet_mask, interface_description, virtual_ip, vlan, vlan_number, interface_status, fetch_date) VALUES (%(ip_address)s, %(device_name)s, %(interface)s, %(interface_ip)s, %(subnet)s, %(subnet_mask)s, %(interface_description)s, %(virtual_ip)s, %(vlan)s, %(vlan_number)s, %(interface_status)s, %(fetch_date)s)]\n[parameters: {'ip_address': 'sandbox-iosxe-latest-1.cisco.com', 'device_name': 'Switch6', 'interface': 'Loopback11', 'interface_ip': '', 'subnet': '172.16.11.0/24', 'subnet_mask': IPAddress('255.255.255.0'), 'interface_description': 'Configured by RESTCONF', 'virtual_ip': '', 'vlan': None, 'vlan_number': '', 'interface_status': 'up', 'fetch_date': datetime.datetime(2000, 1, 1, 0, 0)}]\n(Background on this error at: http://sqlalche.me/e/13/gkpj)"}, {"ip_address": "192.156.30.157", "date": "25-08-2022", "time": "18-26-05", "reason": "Failed to login to host"}, {"ip_address": "192.168.30.154", "date": "25-08-2022", "time": "18-26-05", "reason": "Failed to login to host"}, {"ip_address": "192.168.30.151", "date": "25-08-2022", "time": "18-26-42", "reason": "Exception Occured while Parsing Vlan Keys 'str' object has no attribute 'pop'"}, {"ip_address": "192.168.30.152", "date": "25-08-2022", "time": "18-26-42", "reason": "Exception Occured while Parsing Vlan Keys 'str' object has no attribute 'pop'"}, {"ip_address": "sandbox-iosxe-latest-1.cisco.com", "date": "25-08-2022", "time": "18-27-02", "reason": "Exception Occured while Parsing Vlan Keys 'str' object has no attribute 'pop'"}, {"ip_address": "192.156.30.157", "date": "25-08-2022", "time": "18-27-25", "reason": "Failed to login to host"}, {"ip_address": "192.168.30.154", "date": "25-08-2022", "time": "18-27-25", "reason": "Failed to login to host"}, {"ip_address": "192.168.30.152", "date": "25-08-2022", "time": "18-33-32", "reason": "Exception Occured while Parsing Vlan Keys 'str' object has no attribute 'pop'"}, {"ip_address": "192.168.30.151", "date": "25-08-2022", "time": "18-33-32", "reason": "Exception Occured while Parsing Vlan Keys 'str' object has no attribute 'pop'"}, {"ip_address": "192.168.30.152", "date": "25-08-2022", "time": "18-33-33", "reason": "Failed to insert Data to DB (pymysql.err.OperationalError) (1292, \"Incorrect datetime value: '25-08-2022' for column 'FETCH_DATE' at row 1\")\n[SQL: INSERT INTO ipam_devices_fetch_table (ip_address, device_name, interface, interface_ip, subnet, subnet_mask, interface_description, virtual_ip, vlan, vlan_number, interface_status, fetch_date) VALUES (%(ip_address)s, %(device_name)s, %(interface)s, %(interface_ip)s, %(subnet)s, %(subnet_mask)s, %(interface_description)s, %(virtual_ip)s, %(vlan)s, %(vlan_number)s, %(interface_status)s, %(fetch_date)s)]\n[parameters: {'ip_address': '192.168.30.152', 'device_name': 'Switch4', 'interface': 'Ethernet1/0', 'interface_ip': '', 'subnet': '192.168.30.0/24', 'subnet_mask': IPAddress('255.255.255.0'), 'interface_description': '', 'virtual_ip': '', 'vlan': None, 'vlan_number': '', 'interface_status': 'up', 'fetch_date': '25-08-2022'}]\n(Background on this error at: http://sqlalche.me/e/13/e3q8)"}, {"ip_address": "192.168.30.151", "date": "25-08-2022", "time": "18-33-34", "reason": "Failed to insert Data to DB (pymysql.err.OperationalError) (1292, \"Incorrect datetime value: '25-08-2022' for column 'FETCH_DATE' at row 1\")\n[SQL: INSERT INTO ipam_devices_fetch_table (ip_address, device_name, interface, interface_ip, subnet, subnet_mask, interface_description, virtual_ip, vlan, vlan_number, interface_status, fetch_date) VALUES (%(ip_address)s, %(device_name)s, %(interface)s, %(interface_ip)s, %(subnet)s, %(subnet_mask)s, %(interface_description)s, %(virtual_ip)s, %(vlan)s, %(vlan_number)s, %(interface_status)s, %(fetch_date)s)]\n[parameters: {'ip_address': '192.168.30.151', 'device_name': 'Switch1', 'interface': 'Ethernet2/0', 'interface_ip': '', 'subnet': '192.168.30.0/24', 'subnet_mask': IPAddress('255.255.255.0'), 'interface_description': '', 'virtual_ip': '', 'vlan': None, 'vlan_number': '', 'interface_status': 'up', 'fetch_date': '25-08-2022'}]\n(Background on this error at: http://sqlalche.me/e/13/e3q8)"}, {"ip_address": "sandbox-iosxe-latest-1.cisco.com", "date": "25-08-2022", "time": "18-33-53", "reason": "Exception Occured while Parsing Vlan Keys 'str' object has no attribute 'pop'"}, {"ip_address": "sandbox-iosxe-latest-1.cisco.com", "date": "25-08-2022", "time": "18-33-55", "reason": "Failed to insert Data to DB (pymysql.err.OperationalError) (1292, \"Incorrect datetime value: '25-08-2022' for column 'FETCH_DATE' at row 1\")\n[SQL: INSERT INTO ipam_devices_fetch_table (ip_address, device_name, interface, interface_ip, subnet, subnet_mask, interface_description, virtual_ip, vlan, vlan_number, interface_status, fetch_date) VALUES (%(ip_address)s, %(device_name)s, %(interface)s, %(interface_ip)s, %(subnet)s, %(subnet_mask)s, %(interface_description)s, %(virtual_ip)s, %(vlan)s, %(vlan_number)s, %(interface_status)s, %(fetch_date)s)]\n[parameters: {'ip_address': 'sandbox-iosxe-latest-1.cisco.com', 'device_name': 'Switch6', 'interface': 'GigabitEthernet1', 'interface_ip': '', 'subnet': '10.10.20.0/24', 'subnet_mask': IPAddress('255.255.255.0'), 'interface_description': \"MANAGEMENT INTERFACE - DON'T TOUCH ME\", 'virtual_ip': '', 'vlan': None, 'vlan_number': '', 'interface_status': 'up', 'fetch_date': '25-08-2022'}]\n(Background on this error at: http://sqlalche.me/e/13/e3q8)"}, {"ip_address": "sandbox-iosxe-latest-1.cisco.com", "date": "25-08-2022", "time": "18-33-55", "reason": "Failed to insert Data to DB (pymysql.err.OperationalError) (1292, \"Incorrect datetime value: '25-08-2022' for column 'FETCH_DATE' at row 1\")\n[SQL: INSERT INTO ipam_devices_fetch_table (ip_address, device_name, interface, interface_ip, subnet, subnet_mask, interface_description, virtual_ip, vlan, vlan_number, interface_status, fetch_date) VALUES (%(ip_address)s, %(device_name)s, %(interface)s, %(interface_ip)s, %(subnet)s, %(subnet_mask)s, %(interface_description)s, %(virtual_ip)s, %(vlan)s, %(vlan_number)s, %(interface_status)s, %(fetch_date)s)]\n[parameters: {'ip_address': 'sandbox-iosxe-latest-1.cisco.com', 'device_name': 'Switch6', 'interface': 'Loopback2', 'interface_ip': '', 'subnet': '1.1.1.1/32', 'subnet_mask': IPAddress('255.255.255.255'), 'interface_description': 'Configured by RESTCONF', 'virtual_ip': '', 'vlan': None, 'vlan_number': '', 'interface_status': 'up', 'fetch_date': '25-08-2022'}]\n(Background on this error at: http://sqlalche.me/e/13/e3q8)"}, {"ip_address": "sandbox-iosxe-latest-1.cisco.com", "date": "25-08-2022", "time": "18-33-55", "reason": "Failed to insert Data to DB (pymysql.err.OperationalError) (1292, \"Incorrect datetime value: '25-08-2022' for column 'FETCH_DATE' at row 1\")\n[SQL: INSERT INTO ipam_devices_fetch_table (ip_address, device_name, interface, interface_ip, subnet, subnet_mask, interface_description, virtual_ip, vlan, vlan_number, interface_status, fetch_date) VALUES (%(ip_address)s, %(device_name)s, %(interface)s, %(interface_ip)s, %(subnet)s, %(subnet_mask)s, %(interface_description)s, %(virtual_ip)s, %(vlan)s, %(vlan_number)s, %(interface_status)s, %(fetch_date)s)]\n[parameters: {'ip_address': 'sandbox-iosxe-latest-1.cisco.com', 'device_name': 'Switch6', 'interface': 'Loopback11', 'interface_ip': '', 'subnet': '172.16.11.0/24', 'subnet_mask': IPAddress('255.255.255.0'), 'interface_description': 'Configured by RESTCONF', 'virtual_ip': '', 'vlan': None, 'vlan_number': '', 'interface_status': 'up', 'fetch_date': '25-08-2022'}]\n(Background on this error at: http://sqlalche.me/e/13/e3q8)"}, {"ip_address": "192.168.30.154", "date": "25-08-2022", "time": "18-34-15", "reason": "Failed to login to host"}, {"ip_address": "192.156.30.157", "date": "25-08-2022", "time": "18-34-15", "reason": "Failed to login to host"}, {"ip_address": "192.168.30.152", "date": "25-08-2022", "time": "18-34-31", "reason": "Exception Occured while Parsing Vlan Keys 'str' object has no attribute 'pop'"}, {"ip_address": "192.168.30.151", "date": "25-08-2022", "time": "18-34-31", "reason": "Exception Occured while Parsing Vlan Keys 'str' object has no attribute 'pop'"}, {"ip_address": "sandbox-iosxe-latest-1.cisco.com", "date": "25-08-2022", "time": "18-34-52", "reason": "Exception Occured while Parsing Vlan Keys 'str' object has no attribute 'pop'"}, {"ip_address": "192.156.30.157", "date": "25-08-2022", "time": "18-35-14", "reason": "Failed to login to host"}, {"ip_address": "192.168.30.154", "date": "25-08-2022", "time": "18-35-14", "reason": "Failed to login to host"}]